version: "3.8"
services:
  app:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env

  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/:/tmp/data/
    env_file:
      - .env
