version: "3.8"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - /dbdata:/var/lib/postgresql/data

    env_file:
      - .env

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: bash ./app.sh
    volumes:
      - .:/application_root/

  reverse_proxy:
    image: nginx
    depends_on:
      - app
    ports:
      - "80:80"
    env_file:
      - .env
    volumes:
      - ./nginx_configuration/:/etc/nginx/conf.d/
      - ./static:/static
