version: "3.8"
services:
  app:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME: ${POSTGRES_NAME}
      - POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      - DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      - POSTGRES_USER: ${POSTGRES_USER}

  db:
    image: postgres
    environment:
      - POSTGRES_NAME: ${POSTGRES_NAME}
      - POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      - POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - ./data/:/tmp/data/
